stages:
  - build

build:
  retry:
    max: 2
    when: always
  only:
    - branches
    - master # I suppose that we can work directly on master
    - merge_request
  stage: build
  image: debian:sid
  dependencies: []
  script:
    - apt-get update && apt-get install -y vmdb2 dosfstools qemu-utils qemu-user-static debootstrap binfmt-support time kpartx bmap-tools python3 fakemachine make
    - make yaml
    - mkdir build
    - cp raspi*.yaml build
  artifacts:
    paths:
      - build

variables:
  DEBIAN_FRONTEND: "noninteractive"

